-- start application first for Sequelize to create tables
-- paste the code below into Mysql after you have started the application

use stonker 

insert into companies (symbol,company,sector,checked_at,created_at,updated_at)
values
(  'MMM',  '3M Company', 'Industrials', now() , now() ,now() ),
(  'ABT',  'Abbott Laboratories', 'Health Care', now() , now() ,now() ),
(  'ABBV',  'AbbVie Inc.', 'Health Care', now() , now() ,now() ),
(  'ABMD',  'Abiomed', 'Health Care', now() , now() ,now() ),
(  'ACN',  'Accenture', 'Information Technology', now() , now() ,now() ),
(  'ATVI',  'Activision Blizzard', 'Communication Services', now() , now() ,now() ),
(  'ADBE',  'Adobe Inc.', 'Information Technology', now() , now() ,now() ),
(  'AMD',  'Advanced Micro Devices', 'Information Technology', now() , now() ,now() ),
(  'AAP',  'Advance Auto Parts', 'Consumer Discretionary', now() , now() ,now() ),
(  'AES',  'AES Corp', 'Utilities', now() , now() ,now() ),
(  'AFL',  'Aflac', 'Financials', now() , now() ,now() ),
(  'A',  'Agilent Technologies', 'Health Care', now() , now() ,now() ),
(  'APD',  'Air Products & Chemicals', 'Materials', now() , now() ,now() ),
(  'AKAM',  'Akamai Technologies', 'Information Technology', now() , now() ,now() ),
(  'ALK',  'Alaska Air Group', 'Industrials', now() , now() ,now() ),
(  'ALB',  'Albemarle Corporation', 'Materials', now() , now() ,now() ),
(  'ARE',  'Alexandria Real Estate Equities', 'Real Estate', now() , now() ,now() ),
(  'ALXN',  'Alexion Pharmaceuticals', 'Health Care', now() , now() ,now() ),
(  'ALGN',  'Align Technology', 'Health Care', now() , now() ,now() ),
(  'ALLE',  'Allegion', 'Industrials', now() , now() ,now() ),
(  'LNT',  'Alliant Energy', 'Utilities', now() , now() ,now() ),
(  'ALL',  'Allstate Corp', 'Financials', now() , now() ,now() ),
(  'GOOGL',  'Alphabet Inc. Class A', 'Communication Services', now() , now() ,now() ),
(  'GOOG',  'Alphabet Inc. Class C', 'Communication Services', now() , now() ,now() ),
(  'MO',  'Altria Group Inc', 'Consumer Staples', now() , now() ,now() ),
(  'AMZN',  'Amazon.com Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'AMCR',  'Amcor', 'Materials', now() , now() ,now() ),
(  'AEE',  'Ameren Corp', 'Utilities', now() , now() ,now() ),
(  'AAL',  'American Airlines Group', 'Industrials', now() , now() ,now() ),
(  'AEP',  'American Electric Power', 'Utilities', now() , now() ,now() ),
(  'AXP',  'American Express', 'Financials', now() , now() ,now() ),
(  'AIG',  'American International Group', 'Financials', now() , now() ,now() ),
(  'AMT',  'American Tower Corp.', 'Real Estate', now() , now() ,now() ),
(  'AWK',  'American Water Works', 'Utilities', now() , now() ,now() ),
(  'AMP',  'Ameriprise Financial', 'Financials', now() , now() ,now() ),
(  'ABC',  'AmerisourceBergen', 'Health Care', now() , now() ,now() ),
(  'AME',  'Ametek', 'Industrials', now() , now() ,now() ),
(  'AMGN',  'Amgen Inc.', 'Health Care', now() , now() ,now() ),
(  'APH',  'Amphenol Corp', 'Information Technology', now() , now() ,now() ),
(  'ADI',  'Analog Devices, Inc.', 'Information Technology', now() , now() ,now() ),
(  'ANSS',  'ANSYS, Inc.', 'Information Technology', now() , now() ,now() ),
(  'ANTM',  'Anthem', 'Health Care', now() , now() ,now() ),
(  'AON',  'Aon plc', 'Financials', now() , now() ,now() ),
(  'AOS',  'A.O. Smith Corp', 'Industrials', now() , now() ,now() ),
(  'APA',  'Apache Corporation', 'Energy', now() , now() ,now() ),
(  'AAPL',  'Apple Inc.', 'Information Technology', now() , now() ,now() ),
(  'AMAT',  'Applied Materials Inc.', 'Information Technology', now() , now() ,now() ),
(  'APTV',  'Aptiv PLC', 'Consumer Discretionary', now() , now() ,now() ),
(  'ADM',  'Archer-Daniels-Midland Co', 'Consumer Staples', now() , now() ,now() ),
(  'ANET',  'Arista Networks', 'Information Technology', now() , now() ,now() ),
(  'AJG',  'Arthur J. Gallagher & Co.', 'Financials', now() , now() ,now() ),
(  'AIZ',  'Assurant', 'Financials', now() , now() ,now() ),
(  'T',  'AT&T Inc.', 'Communication Services', now() , now() ,now() ),
(  'ATO',  'Atmos Energy', 'Utilities', now() , now() ,now() ),
(  'ADSK',  'Autodesk Inc.', 'Information Technology', now() , now() ,now() ),
(  'ADP',  'Automatic Data Processing', 'Information Technology', now() , now() ,now() ),
(  'AZO',  'AutoZone Inc', 'Consumer Discretionary', now() , now() ,now() ),
(  'AVB',  'AvalonBay Communities', 'Real Estate', now() , now() ,now() ),
(  'AVY',  'Avery Dennison Corp', 'Materials', now() , now() ,now() ),
(  'BKR',  'Baker Hughes Co', 'Energy', now() , now() ,now() ),
(  'BLL',  'Ball Corp', 'Materials', now() , now() ,now() ),
(  'BAC',  'Bank of America Corp', 'Financials', now() , now() ,now() ),
(  'BK',  'The Bank of New York Mellon', 'Financials', now() , now() ,now() ),
(  'BAX',  'Baxter International Inc.', 'Health Care', now() , now() ,now() ),
(  'BDX',  'Becton Dickinson', 'Health Care', now() , now() ,now() ),
(  'BRK.B',  'Berkshire Hathaway', 'Financials', now() , now() ,now() ),
(  'BBY',  'Best Buy Co. Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'BIO',  'Bio-Rad Laboratories', 'Health Care', now() , now() ,now() ),
(  'BIIB',  'Biogen Inc.', 'Health Care', now() , now() ,now() ),
(  'BLK',  'BlackRock', 'Financials', now() , now() ,now() ),
(  'BA',  'Boeing Company', 'Industrials', now() , now() ,now() ),
(  'BKNG',  'Booking Holdings Inc', 'Consumer Discretionary', now() , now() ,now() ),
(  'BWA',  'BorgWarner', 'Consumer Discretionary', now() , now() ,now() ),
(  'BXP',  'Boston Properties', 'Real Estate', now() , now() ,now() ),
(  'BSX',  'Boston Scientific', 'Health Care', now() , now() ,now() ),
(  'BMY',  'Bristol-Myers Squibb', 'Health Care', now() , now() ,now() ),
(  'AVGO',  'Broadcom Inc.', 'Information Technology', now() , now() ,now() ),
(  'BR',  'Broadridge Financial Solutions', 'Information Technology', now() , now() ,now() ),
(  'BF.B',  'Brown-Forman Corp.', 'Consumer Staples', now() , now() ,now() ),
(  'CHRW',  'C. H. Robinson Worldwide', 'Industrials', now() , now() ,now() ),
(  'COG',  'Cabot Oil & Gas', 'Energy', now() , now() ,now() ),
(  'CDNS',  'Cadence Design Systems', 'Information Technology', now() , now() ,now() ),
(  'CPB',  'Campbell Soup', 'Consumer Staples', now() , now() ,now() ),
(  'COF',  'Capital One Financial', 'Financials', now() , now() ,now() ),
(  'CAH',  'Cardinal Health Inc.', 'Health Care', now() , now() ,now() ),
(  'KMX',  'Carmax Inc', 'Consumer Discretionary', now() , now() ,now() ),
(  'CCL',  'Carnival Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'CARR',  'Carrier Global', 'Industrials', now() , now() ,now() ),
(  'CTLT',  'Catalent', 'Health Care', now() , now() ,now() ),
(  'CAT',  'Caterpillar Inc.', 'Industrials', now() , now() ,now() ),
(  'CBOE',  'Cboe Global Markets', 'Financials', now() , now() ,now() ),
(  'CBRE',  'CBRE Group', 'Real Estate', now() , now() ,now() ),
(  'CDW',  'CDW', 'Information Technology', now() , now() ,now() ),
(  'CE',  'Celanese', 'Materials', now() , now() ,now() ),
(  'CNC',  'Centene Corporation', 'Health Care', now() , now() ,now() ),
(  'CNP',  'CenterPoint Energy', 'Utilities', now() , now() ,now() ),
(  'CERN',  'Cerner', 'Health Care', now() , now() ,now() ),
(  'CF',  'CF Industries Holdings Inc', 'Materials', now() , now() ,now() ),
(  'SCHW',  'Charles Schwab Corporation', 'Financials', now() , now() ,now() ),
(  'CHTR',  'Charter Communications', 'Communication Services', now() , now() ,now() ),
(  'CVX',  'Chevron Corp.', 'Energy', now() , now() ,now() ),
(  'CMG',  'Chipotle Mexican Grill', 'Consumer Discretionary', now() , now() ,now() ),
(  'CB',  'Chubb Limited', 'Financials', now() , now() ,now() ),
(  'CHD',  'Church & Dwight', 'Consumer Staples', now() , now() ,now() ),
(  'CI',  'Cigna', 'Health Care', now() , now() ,now() ),
(  'CINF',  'Cincinnati Financial', 'Financials', now() , now() ,now() ),
(  'CTAS',  'Cintas Corporation', 'Industrials', now() , now() ,now() ),
(  'CSCO',  'Cisco Systems', 'Information Technology', now() , now() ,now() ),
(  'C',  'Citigroup Inc.', 'Financials', now() , now() ,now() ),
(  'CFG',  'Citizens Financial Group', 'Financials', now() , now() ,now() ),
(  'CTXS',  'Citrix Systems', 'Information Technology', now() , now() ,now() ),
(  'CLX',  'The Clorox Company', 'Consumer Staples', now() , now() ,now() ),
(  'CME',  'CME Group Inc.', 'Financials', now() , now() ,now() ),
(  'CMS',  'CMS Energy', 'Utilities', now() , now() ,now() ),
(  'KO',  'Coca-Cola Company', 'Consumer Staples', now() , now() ,now() ),
(  'CTSH',  'Cognizant Technology Solutions', 'Information Technology', now() , now() ,now() ),
(  'CL',  'Colgate-Palmolive', 'Consumer Staples', now() , now() ,now() ),
(  'CMCSA',  'Comcast Corp.', 'Communication Services', now() , now() ,now() ),
(  'CMA',  'Comerica Inc.', 'Financials', now() , now() ,now() ),
(  'CAG',  'Conagra Brands', 'Consumer Staples', now() , now() ,now() ),
(  'COP',  'ConocoPhillips', 'Energy', now() , now() ,now() ),
(  'ED',  'Consolidated Edison', 'Utilities', now() , now() ,now() ),
(  'STZ',  'Constellation Brands', 'Consumer Staples', now() , now() ,now() ),
(  'COO',  'The Cooper Companies', 'Health Care', now() , now() ,now() ),
(  'CPRT',  'Copart Inc', 'Industrials', now() , now() ,now() ),
(  'GLW',  'Corning Inc.', 'Information Technology', now() , now() ,now() ),
(  'CTVA',  'Corteva', 'Materials', now() , now() ,now() ),
(  'COST',  'Costco Wholesale Corp.', 'Consumer Staples', now() , now() ,now() ),
(  'CCI',  'Crown Castle', 'Real Estate', now() , now() ,now() ),
(  'CSX',  'CSX Corp.', 'Industrials', now() , now() ,now() ),
(  'CMI',  'Cummins Inc.', 'Industrials', now() , now() ,now() ),
(  'CVS',  'CVS Health', 'Health Care', now() , now() ,now() ),
(  'DHI',  'D. R. Horton', 'Consumer Discretionary', now() , now() ,now() ),
(  'DHR',  'Danaher Corp.', 'Health Care', now() , now() ,now() ),
(  'DRI',  'Darden Restaurants', 'Consumer Discretionary', now() , now() ,now() ),
(  'DVA',  'DaVita Inc.', 'Health Care', now() , now() ,now() ),
(  'DE',  'Deere & Co.', 'Industrials', now() , now() ,now() ),
(  'DAL',  'Delta Air Lines Inc.', 'Industrials', now() , now() ,now() ),
(  'XRAY',  'Dentsply Sirona', 'Health Care', now() , now() ,now() ),
(  'DVN',  'Devon Energy', 'Energy', now() , now() ,now() ),
(  'DXCM',  'DexCom', 'Health Care', now() , now() ,now() ),
(  'FANG',  'Diamondback Energy', 'Energy', now() , now() ,now() ),
(  'DLR',  'Digital Realty Trust Inc', 'Real Estate', now() , now() ,now() ),
(  'DFS',  'Discover Financial Services', 'Financials', now() , now() ,now() ),
(  'DISCA',  'Discovery, Inc. Series A', 'Communication Services', now() , now() ,now() ),
(  'DISCK',  'Discovery, Inc. Series C', 'Communication Services', now() , now() ,now() ),
(  'DISH',  'Dish Network', 'Communication Services', now() , now() ,now() ),
(  'DG',  'Dollar General', 'Consumer Discretionary', now() , now() ,now() ),
(  'DLTR',  'Dollar Tree', 'Consumer Discretionary', now() , now() ,now() ),
(  'D',  'Dominion Energy', 'Utilities', now() , now() ,now() ),
(  'DPZ',  'Dominos Pizza', 'Consumer Discretionary', now() , now() ,now() ),
(  'DOV',  'Dover Corporation', 'Industrials', now() , now() ,now() ),
(  'DOW',  'Dow Inc.', 'Materials', now() , now() ,now() ),
(  'DTE',  'DTE Energy Co.', 'Utilities', now() , now() ,now() ),
(  'DUK',  'Duke Energy', 'Utilities', now() , now() ,now() ),
(  'DRE',  'Duke Realty Corp', 'Real Estate', now() , now() ,now() ),
(  'DD',  'DuPont de Nemours Inc', 'Materials', now() , now() ,now() ),
(  'DXC',  'DXC Technology', 'Information Technology', now() , now() ,now() ),
(  'EMN',  'Eastman Chemical', 'Materials', now() , now() ,now() ),
(  'ETN',  'Eaton Corporation', 'Industrials', now() , now() ,now() ),
(  'EBAY',  'eBay Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'ECL',  'Ecolab Inc.', 'Materials', now() , now() ,now() ),
(  'EIX',  'Edison Intl', 'Utilities', now() , now() ,now() ),
(  'EW',  'Edwards Lifesciences', 'Health Care', now() , now() ,now() ),
(  'EA',  'Electronic Arts', 'Communication Services', now() , now() ,now() ),
(  'EMR',  'Emerson Electric Company', 'Industrials', now() , now() ,now() ),
(  'ENPH',  'Enphase Energy', 'Information Technology', now() , now() ,now() ),
(  'ETR',  'Entergy Corp.', 'Utilities', now() , now() ,now() ),
(  'EOG',  'EOG Resources', 'Energy', now() , now() ,now() ),
(  'EFX',  'Equifax Inc.', 'Industrials', now() , now() ,now() ),
(  'EQIX',  'Equinix', 'Real Estate', now() , now() ,now() ),
(  'EQR',  'Equity Residential', 'Real Estate', now() , now() ,now() ),
(  'ESS',  'Essex Property Trust, Inc.', 'Real Estate', now() , now() ,now() ),
(  'EL',  'Estée Lauder Companies', 'Consumer Staples', now() , now() ,now() ),
(  'ETSY',  'Etsy', 'Consumer Discretionary', now() , now() ,now() ),
(  'EVRG',  'Evergy', 'Utilities', now() , now() ,now() ),
(  'ES',  'Eversource Energy', 'Utilities', now() , now() ,now() ),
(  'RE',  'Everest Re Group Ltd.', 'Financials', now() , now() ,now() ),
(  'EXC',  'Exelon Corp.', 'Utilities', now() , now() ,now() ),
(  'EXPE',  'Expedia Group', 'Consumer Discretionary', now() , now() ,now() ),
(  'EXPD',  'Expeditors', 'Industrials', now() , now() ,now() ),
(  'EXR',  'Extra Space Storage', 'Real Estate', now() , now() ,now() ),
(  'XOM',  'Exxon Mobil Corp.', 'Energy', now() , now() ,now() ),
(  'FFIV',  'F5 Networks', 'Information Technology', now() , now() ,now() ),
(  'FB',  'Facebook, Inc.', 'Communication Services', now() , now() ,now() ),
(  'FAST',  'Fastenal Co', 'Industrials', now() , now() ,now() ),
(  'FRT',  'Federal Realty Investment Trust', 'Real Estate', now() , now() ,now() ),
(  'FDX',  'FedEx Corporation', 'Industrials', now() , now() ,now() ),
(  'FIS',  'Fidelity National Information Services', 'Information Technology', now() , now() ,now() ),
(  'FITB',  'Fifth Third Bancorp', 'Financials', now() , now() ,now() ),
(  'FE',  'FirstEnergy Corp', 'Utilities', now() , now() ,now() ),
(  'FRC',  'First Republic Bank', 'Financials', now() , now() ,now() ),
(  'FISV',  'Fiserv Inc', 'Information Technology', now() , now() ,now() ),
(  'FLT',  'FleetCor Technologies Inc', 'Information Technology', now() , now() ,now() ),
(  'FLIR',  'FLIR Systems', 'Information Technology', now() , now() ,now() ),
(  'FLS',  'Flowserve Corporation', 'Industrials', now() , now() ,now() ),
(  'FMC',  'FMC Corporation', 'Materials', now() , now() ,now() ),
(  'F',  'Ford Motor Company', 'Consumer Discretionary', now() , now() ,now() ),
(  'FTNT',  'Fortinet', 'Information Technology', now() , now() ,now() ),
(  'FTV',  'Fortive Corp', 'Industrials', now() , now() ,now() ),
(  'FBHS',  'Fortune Brands Home & Security', 'Industrials', now() , now() ,now() ),
(  'FOXA',  'Fox Corporation (Class A)', 'Communication Services', now() , now() ,now() ),
(  'FOX',  'Fox Corporation (Class B)', 'Communication Services', now() , now() ,now() ),
(  'BEN',  'Franklin Resources', 'Financials', now() , now() ,now() ),
(  'FCX',  'Freeport-McMoRan Inc.', 'Materials', now() , now() ,now() ),
(  'GPS',  'Gap Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'GRMN',  'Garmin Ltd.', 'Consumer Discretionary', now() , now() ,now() ),
(  'IT',  'Gartner Inc', 'Information Technology', now() , now() ,now() ),
(  'GD',  'General Dynamics', 'Industrials', now() , now() ,now() ),
(  'GE',  'General Electric', 'Industrials', now() , now() ,now() ),
(  'GIS',  'General Mills', 'Consumer Staples', now() , now() ,now() ),
(  'GM',  'General Motors', 'Consumer Discretionary', now() , now() ,now() ),
(  'GPC',  'Genuine Parts', 'Consumer Discretionary', now() , now() ,now() ),
(  'GILD',  'Gilead Sciences', 'Health Care', now() , now() ,now() ),
(  'GL',  'Globe Life Inc.', 'Financials', now() , now() ,now() ),
(  'GPN',  'Global Payments Inc.', 'Information Technology', now() , now() ,now() ),
(  'GS',  'Goldman Sachs Group', 'Financials', now() , now() ,now() ),
(  'GWW',  'Grainger W.W. Inc.', 'Industrials', now() , now() ,now() ),
(  'HAL',  'Halliburton Co.', 'Energy', now() , now() ,now() ),
(  'HBI',  'Hanesbrands Inc', 'Consumer Discretionary', now() , now() ,now() ),
(  'HIG',  'Hartford Financial Svc.Gp.', 'Financials', now() , now() ,now() ),
(  'HAS',  'Hasbro Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'HCA',  'HCA Healthcare', 'Health Care', now() , now() ,now() ),
(  'PEAK',  'Healthpeak Properties', 'Real Estate', now() , now() ,now() ),
(  'HSIC',  'Henry Schein', 'Health Care', now() , now() ,now() ),
(  'HSY',  'The Hershey Company', 'Consumer Staples', now() , now() ,now() ),
(  'HES',  'Hess Corporation', 'Energy', now() , now() ,now() ),
(  'HPE',  'Hewlett Packard Enterprise', 'Information Technology', now() , now() ,now() ),
(  'HLT',  'Hilton Worldwide Holdings Inc', 'Consumer Discretionary', now() , now() ,now() ),
(  'HFC',  'HollyFrontier Corp', 'Energy', now() , now() ,now() ),
(  'HOLX',  'Hologic', 'Health Care', now() , now() ,now() ),
(  'HD',  'Home Depot', 'Consumer Discretionary', now() , now() ,now() ),
(  'HON',  'Honeywell Intl Inc.', 'Industrials', now() , now() ,now() ),
(  'HRL',  'Hormel Foods Corp.', 'Consumer Staples', now() , now() ,now() ),
(  'HST',  'Host Hotels & Resorts', 'Real Estate', now() , now() ,now() ),
(  'HWM',  'Howmet Aerospace', 'Industrials', now() , now() ,now() ),
(  'HPQ',  'HP Inc.', 'Information Technology', now() , now() ,now() ),
(  'HUM',  'Humana Inc.', 'Health Care', now() , now() ,now() ),
(  'HBAN',  'Huntington Bancshares', 'Financials', now() , now() ,now() ),
(  'HII',  'Huntington Ingalls Industries', 'Industrials', now() , now() ,now() ),
(  'IEX',  'IDEX Corporation', 'Industrials', now() , now() ,now() ),
(  'IDXX',  'Idexx Laboratories', 'Health Care', now() , now() ,now() ),
(  'INFO',  'IHS Markit', 'Industrials', now() , now() ,now() ),
(  'ITW',  'Illinois Tool Works', 'Industrials', now() , now() ,now() ),
(  'ILMN',  'Illumina Inc', 'Health Care', now() , now() ,now() ),
(  'INCY',  'Incyte', 'Health Care', now() , now() ,now() ),
(  'IR',  'Ingersoll Rand', 'Industrials', now() , now() ,now() ),
(  'INTC',  'Intel Corp.', 'Information Technology', now() , now() ,now() ),
(  'ICE',  'Intercontinental Exchange', 'Financials', now() , now() ,now() ),
(  'IBM',  'International Business Machines', 'Information Technology', now() , now() ,now() ),
(  'IP',  'International Paper', 'Materials', now() , now() ,now() ),
(  'IPG',  'Interpublic Group', 'Communication Services', now() , now() ,now() ),
(  'IFF',  'International Flavors & Fragrances', 'Materials', now() , now() ,now() ),
(  'INTU',  'Intuit Inc.', 'Information Technology', now() , now() ,now() ),
(  'ISRG',  'Intuitive Surgical Inc.', 'Health Care', now() , now() ,now() ),
(  'IVZ',  'Invesco Ltd.', 'Financials', now() , now() ,now() ),
(  'IPGP',  'IPG Photonics Corp.', 'Information Technology', now() , now() ,now() ),
(  'IQV',  'IQVIA Holdings Inc.', 'Health Care', now() , now() ,now() ),
(  'IRM',  'Iron Mountain Incorporated', 'Real Estate', now() , now() ,now() ),
(  'JKHY',  'Jack Henry & Associates', 'Information Technology', now() , now() ,now() ),
(  'J',  'Jacobs Engineering Group', 'Industrials', now() , now() ,now() ),
(  'JBHT',  'J. B. Hunt Transport Services', 'Industrials', now() , now() ,now() ),
(  'SJM',  'JM Smucker', 'Consumer Staples', now() , now() ,now() ),
(  'JNJ',  'Johnson & Johnson', 'Health Care', now() , now() ,now() ),
(  'JCI',  'Johnson Controls International', 'Industrials', now() , now() ,now() ),
(  'JPM',  'JPMorgan Chase & Co.', 'Financials', now() , now() ,now() ),
(  'JNPR',  'Juniper Networks', 'Information Technology', now() , now() ,now() ),
(  'KSU',  'Kansas City Southern', 'Industrials', now() , now() ,now() ),
(  'K',  'Kellogg Co.', 'Consumer Staples', now() , now() ,now() ),
(  'KEY',  'KeyCorp', 'Financials', now() , now() ,now() ),
(  'KEYS',  'Keysight Technologies', 'Information Technology', now() , now() ,now() ),
(  'KMB',  'Kimberly-Clark', 'Consumer Staples', now() , now() ,now() ),
(  'KIM',  'Kimco Realty', 'Real Estate', now() , now() ,now() ),
(  'KMI',  'Kinder Morgan', 'Energy', now() , now() ,now() ),
(  'KLAC',  'KLA Corporation', 'Information Technology', now() , now() ,now() ),
(  'KHC',  'Kraft Heinz Co', 'Consumer Staples', now() , now() ,now() ),
(  'KR',  'Kroger Co.', 'Consumer Staples', now() , now() ,now() ),
(  'LB',  'L Brands Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'LHX',  'L3Harris Technologies', 'Industrials', now() , now() ,now() ),
(  'LH',  'Laboratory Corp. of America Holding', 'Health Care', now() , now() ,now() ),
(  'LRCX',  'Lam Research', 'Information Technology', now() , now() ,now() ),
(  'LW',  'Lamb Weston Holdings Inc', 'Consumer Staples', now() , now() ,now() ),
(  'LVS',  'Las Vegas Sands', 'Consumer Discretionary', now() , now() ,now() ),
(  'LEG',  'Leggett & Platt', 'Consumer Discretionary', now() , now() ,now() ),
(  'LDOS',  'Leidos Holdings', 'Information Technology', now() , now() ,now() ),
(  'LEN',  'Lennar Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'LLY',  'Lilly (Eli) & Co.', 'Health Care', now() , now() ,now() ),
(  'LNC',  'Lincoln National', 'Financials', now() , now() ,now() ),
(  'LIN',  'Linde plc', 'Materials', now() , now() ,now() ),
(  'LYV',  'Live Nation Entertainment', 'Communication Services', now() , now() ,now() ),
(  'LKQ',  'LKQ Corporation', 'Consumer Discretionary', now() , now() ,now() ),
(  'LMT',  'Lockheed Martin Corp.', 'Industrials', now() , now() ,now() ),
(  'L',  'Loews Corp.', 'Financials', now() , now() ,now() ),
(  'LOW',  'Lowes Cos.', 'Consumer Discretionary', now() , now() ,now() ),
(  'LUMN',  'Lumen Technologies', 'Communication Services', now() , now() ,now() ),
(  'LYB',  'LyondellBasell', 'Materials', now() , now() ,now() ),
(  'MTB',  'M&T Bank', 'Financials', now() , now() ,now() ),
(  'MRO',  'Marathon Oil Corp.', 'Energy', now() , now() ,now() ),
(  'MPC',  'Marathon Petroleum', 'Energy', now() , now() ,now() ),
(  'MKTX',  'MarketAxess', 'Financials', now() , now() ,now() ),
(  'MAR',  'Marriott International', 'Consumer Discretionary', now() , now() ,now() ),
(  'MMC',  'Marsh & McLennan', 'Financials', now() , now() ,now() ),
(  'MLM',  'Martin Marietta Materials', 'Materials', now() , now() ,now() ),
(  'MAS',  'Masco Corp.', 'Industrials', now() , now() ,now() ),
(  'MA',  'Mastercard Inc.', 'Information Technology', now() , now() ,now() ),
(  'MKC',  'McCormick & Co.', 'Consumer Staples', now() , now() ,now() ),
(  'MXIM',  'Maxim Integrated Products', 'Information Technology', now() , now() ,now() ),
(  'MCD',  'McDonalds Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'MCK',  'McKesson Corp.', 'Health Care', now() , now() ,now() ),
(  'MDT',  'Medtronic plc', 'Health Care', now() , now() ,now() ),
(  'MRK',  'Merck & Co.', 'Health Care', now() , now() ,now() ),
(  'MET',  'MetLife Inc.', 'Financials', now() , now() ,now() ),
(  'MTD',  'Mettler Toledo', 'Health Care', now() , now() ,now() ),
(  'MGM',  'MGM Resorts International', 'Consumer Discretionary', now() , now() ,now() ),
(  'MCHP',  'Microchip Technology', 'Information Technology', now() , now() ,now() ),
(  'MU',  'Micron Technology', 'Information Technology', now() , now() ,now() ),
(  'MSFT',  'Microsoft Corp.', 'Information Technology', now() , now() ,now() ),
(  'MAA',  'Mid-America Apartments', 'Real Estate', now() , now() ,now() ),
(  'MHK',  'Mohawk Industries', 'Consumer Discretionary', now() , now() ,now() ),
(  'TAP',  'Molson Coors Beverage Company', 'Consumer Staples', now() , now() ,now() ),
(  'MDLZ',  'Mondelez International', 'Consumer Staples', now() , now() ,now() ),
(  'MNST',  'Monster Beverage', 'Consumer Staples', now() , now() ,now() ),
(  'MCO',  'Moodys Corp', 'Financials', now() , now() ,now() ),
(  'MS',  'Morgan Stanley', 'Financials', now() , now() ,now() ),
(  'MOS',  'The Mosaic Company', 'Materials', now() , now() ,now() ),
(  'MSI',  'Motorola Solutions Inc.', 'Information Technology', now() , now() ,now() ),
(  'MSCI',  'MSCI Inc', 'Financials', now() , now() ,now() ),
(  'NDAQ',  'Nasdaq, Inc.', 'Financials', now() , now() ,now() ),
(  'NTAP',  'NetApp', 'Information Technology', now() , now() ,now() ),
(  'NFLX',  'Netflix Inc.', 'Communication Services', now() , now() ,now() ),
(  'NWL',  'Newell Brands', 'Consumer Discretionary', now() , now() ,now() ),
(  'NEM',  'Newmont Corporation', 'Materials', now() , now() ,now() ),
(  'NWSA',  'News Corp Class A', 'Communication Services', now() , now() ,now() ),
(  'NWS',  'News Corp Class B', 'Communication Services', now() , now() ,now() ),
(  'NEE',  'NextEra Energy', 'Utilities', now() , now() ,now() ),
(  'NLSN',  'Nielsen Holdings', 'Industrials', now() , now() ,now() ),
(  'NKE',  'Nike, Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'NI',  'NiSource Inc.', 'Utilities', now() , now() ,now() ),
(  'NSC',  'Norfolk Southern Corp.', 'Industrials', now() , now() ,now() ),
(  'NTRS',  'Northern Trust Corp.', 'Financials', now() , now() ,now() ),
(  'NOC',  'Northrop Grumman', 'Industrials', now() , now() ,now() ),
(  'NLOK',  'NortonLifeLock', 'Information Technology', now() , now() ,now() ),
(  'NCLH',  'Norwegian Cruise Line Holdings', 'Consumer Discretionary', now() , now() ,now() ),
(  'NOV',  'NOV Inc.', 'Energy', now() , now() ,now() ),
(  'NRG',  'NRG Energy', 'Utilities', now() , now() ,now() ),
(  'NUE',  'Nucor Corp.', 'Materials', now() , now() ,now() ),
(  'NVDA',  'Nvidia Corporation', 'Information Technology', now() , now() ,now() ),
(  'NVR',  'NVR, Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'ORLY',  'OReilly Automotive', 'Consumer Discretionary', now() , now() ,now() ),
(  'OXY',  'Occidental Petroleum', 'Energy', now() , now() ,now() ),
(  'ODFL',  'Old Dominion Freight Line', 'Industrials', now() , now() ,now() ),
(  'OMC',  'Omnicom Group', 'Communication Services', now() , now() ,now() ),
(  'OKE',  'Oneok', 'Energy', now() , now() ,now() ),
(  'ORCL',  'Oracle Corp.', 'Information Technology', now() , now() ,now() ),
(  'OTIS',  'Otis Worldwide', 'Industrials', now() , now() ,now() ),
(  'PCAR',  'Paccar', 'Industrials', now() , now() ,now() ),
(  'PKG',  'Packaging Corporation of America', 'Materials', now() , now() ,now() ),
(  'PH',  'Parker-Hannifin', 'Industrials', now() , now() ,now() ),
(  'PAYX',  'Paychex Inc.', 'Information Technology', now() , now() ,now() ),
(  'PAYC',  'Paycom', 'Information Technology', now() , now() ,now() ),
(  'PYPL',  'PayPal', 'Information Technology', now() , now() ,now() ),
(  'PNR',  'Pentair plc', 'Industrials', now() , now() ,now() ),
(  'PBCT',  'Peoples United Financial', 'Financials', now() , now() ,now() ),
(  'PEP',  'PepsiCo Inc.', 'Consumer Staples', now() , now() ,now() ),
(  'PKI',  'PerkinElmer', 'Health Care', now() , now() ,now() ),
(  'PRGO',  'Perrigo', 'Health Care', now() , now() ,now() ),
(  'PFE',  'Pfizer Inc.', 'Health Care', now() , now() ,now() ),
(  'PM',  'Philip Morris International', 'Consumer Staples', now() , now() ,now() ),
(  'PSX',  'Phillips 66', 'Energy', now() , now() ,now() ),
(  'PNW',  'Pinnacle West Capital', 'Utilities', now() , now() ,now() ),
(  'PXD',  'Pioneer Natural Resources', 'Energy', now() , now() ,now() ),
(  'PNC',  'PNC Financial Services', 'Financials', now() , now() ,now() ),
(  'POOL',  'Pool Corporation', 'Consumer Discretionary', now() , now() ,now() ),
(  'PPG',  'PPG Industries', 'Materials', now() , now() ,now() ),
(  'PPL',  'PPL Corp.', 'Utilities', now() , now() ,now() ),
(  'PFG',  'Principal Financial Group', 'Financials', now() , now() ,now() ),
(  'PG',  'Procter & Gamble', 'Consumer Staples', now() , now() ,now() ),
(  'PGR',  'Progressive Corp.', 'Financials', now() , now() ,now() ),
(  'PLD',  'Prologis', 'Real Estate', now() , now() ,now() ),
(  'PRU',  'Prudential Financial', 'Financials', now() , now() ,now() ),
(  'PEG',  'Public Service Enterprise Group PSEG', 'Utilities', now() , now() ,now() ),
(  'PSA',  'Public Storage', 'Real Estate', now() , now() ,now() ),
(  'PHM',  'PulteGroup', 'Consumer Discretionary', now() , now() ,now() ),
(  'PVH',  'PVH Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'QRVO',  'Qorvo', 'Information Technology', now() , now() ,now() ),
(  'PWR',  'Quanta Services Inc.', 'Industrials', now() , now() ,now() ),
(  'QCOM',  'Qualcomm', 'Information Technology', now() , now() ,now() ),
(  'DGX',  'Quest Diagnostics', 'Health Care', now() , now() ,now() ),
(  'RL',  'Ralph Lauren Corporation', 'Consumer Discretionary', now() , now() ,now() ),
(  'RJF',  'Raymond James Financial', 'Financials', now() , now() ,now() ),
(  'RTX',  'Raytheon Technologies', 'Industrials', now() , now() ,now() ),
(  'O',  'Realty Income Corporation', 'Real Estate', now() , now() ,now() ),
(  'REG',  'Regency Centers Corporation', 'Real Estate', now() , now() ,now() ),
(  'REGN',  'Regeneron Pharmaceuticals', 'Health Care', now() , now() ,now() ),
(  'RF',  'Regions Financial Corp.', 'Financials', now() , now() ,now() ),
(  'RSG',  'Republic Services Inc', 'Industrials', now() , now() ,now() ),
(  'RMD',  'ResMed', 'Health Care', now() , now() ,now() ),
(  'RHI',  'Robert Half International', 'Industrials', now() , now() ,now() ),
(  'ROK',  'Rockwell Automation Inc.', 'Industrials', now() , now() ,now() ),
(  'ROL',  'Rollins, Inc.', 'Industrials', now() , now() ,now() ),
(  'ROP',  'Roper Technologies', 'Industrials', now() , now() ,now() ),
(  'ROST',  'Ross Stores', 'Consumer Discretionary', now() , now() ,now() ),
(  'RCL',  'Royal Caribbean Group', 'Consumer Discretionary', now() , now() ,now() ),
(  'SPGI',  'S&P Global Inc.', 'Financials', now() , now() ,now() ),
(  'CRM',  'Salesforce.com', 'Information Technology', now() , now() ,now() ),
(  'SBAC',  'SBA Communications', 'Real Estate', now() , now() ,now() ),
(  'SLB',  'Schlumberger Ltd.', 'Energy', now() , now() ,now() ),
(  'STX',  'Seagate Technology', 'Information Technology', now() , now() ,now() ),
(  'SEE',  'Sealed Air', 'Materials', now() , now() ,now() ),
(  'SRE',  'Sempra Energy', 'Utilities', now() , now() ,now() ),
(  'NOW',  'ServiceNow', 'Information Technology', now() , now() ,now() ),
(  'SHW',  'Sherwin-Williams', 'Materials', now() , now() ,now() ),
(  'SPG',  'Simon Property Group Inc', 'Real Estate', now() , now() ,now() ),
(  'SWKS',  'Skyworks Solutions', 'Information Technology', now() , now() ,now() ),
(  'SLG',  'SL Green Realty', 'Real Estate', now() , now() ,now() ),
(  'SNA',  'Snap-on', 'Industrials', now() , now() ,now() ),
(  'SO',  'Southern Company', 'Utilities', now() , now() ,now() ),
(  'LUV',  'Southwest Airlines', 'Industrials', now() , now() ,now() ),
(  'SWK',  'Stanley Black & Decker', 'Industrials', now() , now() ,now() ),
(  'SBUX',  'Starbucks Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'STT',  'State Street Corp.', 'Financials', now() , now() ,now() ),
(  'STE',  'Steris', 'Health Care', now() , now() ,now() ),
(  'SYK',  'Stryker Corp.', 'Health Care', now() , now() ,now() ),
(  'SIVB',  'SVB Financial', 'Financials', now() , now() ,now() ),
(  'SYF',  'Synchrony Financial', 'Financials', now() , now() ,now() ),
(  'SNPS',  'Synopsys Inc.', 'Information Technology', now() , now() ,now() ),
(  'SYY',  'Sysco Corp.', 'Consumer Staples', now() , now() ,now() ),
(  'TMUS',  'T-Mobile US', 'Communication Services', now() , now() ,now() ),
(  'TROW',  'T. Rowe Price Group', 'Financials', now() , now() ,now() ),
(  'TTWO',  'Take-Two Interactive', 'Communication Services', now() , now() ,now() ),
(  'TPR',  'Tapestry, Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'TGT',  'Target Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'TEL',  'TE Connectivity Ltd.', 'Information Technology', now() , now() ,now() ),
(  'FTI',  'TechnipFMC', 'Energy', now() , now() ,now() ),
(  'TDY',  'Teledyne Technologies', 'Industrials', now() , now() ,now() ),
(  'TFX',  'Teleflex', 'Health Care', now() , now() ,now() ),
(  'TER',  'Teradyne', 'Information Technology', now() , now() ,now() ),
(  'TSLA',  'Tesla, Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'TXN',  'Texas Instruments', 'Information Technology', now() , now() ,now() ),
(  'TXT',  'Textron Inc.', 'Industrials', now() , now() ,now() ),
(  'TMO',  'Thermo Fisher Scientific', 'Health Care', now() , now() ,now() ),
(  'TJX',  'TJX Companies Inc.', 'Consumer Discretionary', now() , now() ,now() ),
(  'TSCO',  'Tractor Supply Company', 'Consumer Discretionary', now() , now() ,now() ),
(  'TT',  'Trane Technologies plc', 'Industrials', now() , now() ,now() ),
(  'TDG',  'TransDigm Group', 'Industrials', now() , now() ,now() ),
(  'TRV',  'The Travelers Companies', 'Financials', now() , now() ,now() ),
(  'TRMB',  'Trimble Inc.', 'Information Technology', now() , now() ,now() ),
(  'TFC',  'Truist Financial', 'Financials', now() , now() ,now() ),
(  'TWTR',  'Twitter, Inc.', 'Communication Services', now() , now() ,now() ),
(  'TYL',  'Tyler Technologies', 'Information Technology', now() , now() ,now() ),
(  'TSN',  'Tyson Foods', 'Consumer Staples', now() , now() ,now() ),
(  'UDR',  'UDR, Inc.', 'Real Estate', now() , now() ,now() ),
(  'ULTA',  'Ulta Beauty', 'Consumer Discretionary', now() , now() ,now() ),
(  'USB',  'U.S. Bancorp', 'Financials', now() , now() ,now() ),
(  'UAA',  'Under Armour Class A', 'Consumer Discretionary', now() , now() ,now() ),
(  'UA',  'Under Armour Class C', 'Consumer Discretionary', now() , now() ,now() ),
(  'UNP',  'Union Pacific Corp', 'Industrials', now() , now() ,now() ),
(  'UAL',  'United Airlines Holdings', 'Industrials', now() , now() ,now() ),
(  'UNH',  'UnitedHealth Group Inc.', 'Health Care', now() , now() ,now() ),
(  'UPS',  'United Parcel Service', 'Industrials', now() , now() ,now() ),
(  'URI',  'United Rentals, Inc.', 'Industrials', now() , now() ,now() ),
(  'UHS',  'Universal Health Services', 'Health Care', now() , now() ,now() ),
(  'UNM',  'Unum Group', 'Financials', now() , now() ,now() ),
(  'VLO',  'Valero Energy', 'Energy', now() , now() ,now() ),
(  'VAR',  'Varian Medical Systems', 'Health Care', now() , now() ,now() ),
(  'VTR',  'Ventas Inc', 'Real Estate', now() , now() ,now() ),
(  'VRSN',  'Verisign Inc.', 'Information Technology', now() , now() ,now() ),
(  'VRSK',  'Verisk Analytics', 'Industrials', now() , now() ,now() ),
(  'VZ',  'Verizon Communications', 'Communication Services', now() , now() ,now() ),
(  'VRTX',  'Vertex Pharmaceuticals Inc', 'Health Care', now() , now() ,now() ),
(  'VFC',  'VF Corporation', 'Consumer Discretionary', now() , now() ,now() ),
(  'VIAC',  'ViacomCBS', 'Communication Services', now() , now() ,now() ),
(  'VTRS',  'Viatris', 'Health Care', now() , now() ,now() ),
(  'V',  'Visa Inc.', 'Information Technology', now() , now() ,now() ),
(  'VNT',  'Vontier', 'Information Technology', now() , now() ,now() ),
(  'VNO',  'Vornado Realty Trust', 'Real Estate', now() , now() ,now() ),
(  'VMC',  'Vulcan Materials', 'Materials', now() , now() ,now() ),
(  'WRB',  'W. R. Berkley Corporation', 'Financials', now() , now() ,now() ),
(  'WAB',  'Westinghouse Air Brake Technologies Corp', 'Industrials', now() , now() ,now() ),
(  'WMT',  'Walmart', 'Consumer Staples', now() , now() ,now() ),
(  'WBA',  'Walgreens Boots Alliance', 'Consumer Staples', now() , now() ,now() ),
(  'DIS',  'The Walt Disney Company', 'Communication Services', now() , now() ,now() ),
(  'WM',  'Waste Management Inc.', 'Industrials', now() , now() ,now() ),
(  'WAT',  'Waters Corporation', 'Health Care', now() , now() ,now() ),
(  'WEC',  'WEC Energy Group', 'Utilities', now() , now() ,now() ),
(  'WFC',  'Wells Fargo', 'Financials', now() , now() ,now() ),
(  'WELL',  'Welltower Inc.', 'Real Estate', now() , now() ,now() ),
(  'WST',  'West Pharmaceutical Services', 'Health Care', now() , now() ,now() ),
(  'WDC',  'Western Digital', 'Information Technology', now() , now() ,now() ),
(  'WU',  'Western Union Co', 'Information Technology', now() , now() ,now() ),
(  'WRK',  'WestRock', 'Materials', now() , now() ,now() ),
(  'WY',  'Weyerhaeuser', 'Real Estate', now() , now() ,now() ),
(  'WHR',  'Whirlpool Corp.', 'Consumer Discretionary', now() , now() ,now() ),
(  'WMB',  'Williams Companies', 'Energy', now() , now() ,now() ),
(  'WLTW',  'Willis Towers Watson', 'Financials', now() , now() ,now() ),
(  'WYNN',  'Wynn Resorts Ltd', 'Consumer Discretionary', now() , now() ,now() ),
(  'XEL',  'Xcel Energy Inc', 'Utilities', now() , now() ,now() ),
(  'XRX',  'Xerox', 'Information Technology', now() , now() ,now() ),
(  'XLNX',  'Xilinx', 'Information Technology', now() , now() ,now() ),
(  'XYL',  'Xylem Inc.', 'Industrials', now() , now() ,now() ),
(  'YUM',  'Yum! Brands Inc', 'Consumer Discretionary', now() , now() ,now() ),
(  'ZBRA',  'Zebra Technologies', 'Information Technology', now() , now() ,now() ),
(  'ZBH',  'Zimmer Biomet', 'Health Care', now() , now() ,now() ),
(  'ZION',  'Zions Bancorp', 'Financials', now() , now() ,now() ),
(  'ZTS',  'Zoetis', 'Health Care', now() , now() ,now() )

-- run the code below to set the checked at date to what you want


-- use stonker;
-- SET SQL_SAFE_UPDATES=0;
-- update stonker.companies
-- set checked_at = (cast("2021-02-15" as date));
-- SET SQL_SAFE_UPDATES=1;

