-- paste this into server.js 
const monday = new Date('2021-02-15')
db.Company.bulkCreate([
{ symbol: `MMM`, company: `3M Company`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ABT`, company: `Abbott Laboratories`, sector: `Health Care`, checkedAt: monday },
{ symbol: `ABBV`, company: `AbbVie Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `ABMD`, company: `Abiomed`, sector: `Health Care`, checkedAt: monday },
{ symbol: `ACN`, company: `Accenture`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ATVI`, company: `Activision Blizzard`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `ADBE`, company: `Adobe Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `AMD`, company: `Advanced Micro Devices`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `AAP`, company: `Advance Auto Parts`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `AES`, company: `AES Corp`, sector: `Utilities`, checkedAt: monday },
{ symbol: `AFL`, company: `Aflac`, sector: `Financials`, checkedAt: monday },
{ symbol: `A`, company: `Agilent Technologies`, sector: `Health Care`, checkedAt: monday },
{ symbol: `APD`, company: `Air Products & Chemicals`, sector: `Materials`, checkedAt: monday },
{ symbol: `AKAM`, company: `Akamai Technologies`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ALK`, company: `Alaska Air Group`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ALB`, company: `Albemarle Corporation`, sector: `Materials`, checkedAt: monday },
{ symbol: `ARE`, company: `Alexandria Real Estate Equities`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `ALXN`, company: `Alexion Pharmaceuticals`, sector: `Health Care`, checkedAt: monday },
{ symbol: `ALGN`, company: `Align Technology`, sector: `Health Care`, checkedAt: monday },
{ symbol: `ALLE`, company: `Allegion`, sector: `Industrials`, checkedAt: monday },
{ symbol: `LNT`, company: `Alliant Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `ALL`, company: `Allstate Corp`, sector: `Financials`, checkedAt: monday },
{ symbol: `GOOGL`, company: `Alphabet Inc. (Class A)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `GOOG`, company: `Alphabet Inc. (Class C)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `MO`, company: `Altria Group Inc`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `AMZN`, company: `Amazon.com Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `AMCR`, company: `Amcor`, sector: `Materials`, checkedAt: monday },
{ symbol: `AEE`, company: `Ameren Corp`, sector: `Utilities`, checkedAt: monday },
{ symbol: `AAL`, company: `American Airlines Group`, sector: `Industrials`, checkedAt: monday },
{ symbol: `AEP`, company: `American Electric Power`, sector: `Utilities`, checkedAt: monday },
{ symbol: `AXP`, company: `American Express`, sector: `Financials`, checkedAt: monday },
{ symbol: `AIG`, company: `American International Group`, sector: `Financials`, checkedAt: monday },
{ symbol: `AMT`, company: `American Tower Corp.`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `AWK`, company: `American Water Works`, sector: `Utilities`, checkedAt: monday },
{ symbol: `AMP`, company: `Ameriprise Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `ABC`, company: `AmerisourceBergen`, sector: `Health Care`, checkedAt: monday },
{ symbol: `AME`, company: `Ametek`, sector: `Industrials`, checkedAt: monday },
{ symbol: `AMGN`, company: `Amgen Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `APH`, company: `Amphenol Corp`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ADI`, company: `Analog Devices, Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ANSS`, company: `ANSYS, Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ANTM`, company: `Anthem`, sector: `Health Care`, checkedAt: monday },
{ symbol: `AON`, company: `Aon plc`, sector: `Financials`, checkedAt: monday },
{ symbol: `AOS`, company: `A.O. Smith Corp`, sector: `Industrials`, checkedAt: monday },
{ symbol: `APA`, company: `Apache Corporation`, sector: `Energy`, checkedAt: monday },
{ symbol: `AAPL`, company: `Apple Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `AMAT`, company: `Applied Materials Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `APTV`, company: `Aptiv PLC`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `ADM`, company: `Archer-Daniels-Midland Co`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `ANET`, company: `Arista Networks`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `AJG`, company: `Arthur J. Gallagher & Co.`, sector: `Financials`, checkedAt: monday },
{ symbol: `AIZ`, company: `Assurant`, sector: `Financials`, checkedAt: monday },
{ symbol: `T`, company: `AT&T Inc.`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `ATO`, company: `Atmos Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `ADSK`, company: `Autodesk Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ADP`, company: `Automatic Data Processing`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `AZO`, company: `AutoZone Inc`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `AVB`, company: `AvalonBay Communities`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `AVY`, company: `Avery Dennison Corp`, sector: `Materials`, checkedAt: monday },
{ symbol: `BKR`, company: `Baker Hughes Co`, sector: `Energy`, checkedAt: monday },
{ symbol: `BLL`, company: `Ball Corp`, sector: `Materials`, checkedAt: monday },
{ symbol: `BAC`, company: `Bank of America Corp`, sector: `Financials`, checkedAt: monday },
{ symbol: `BK`, company: `The Bank of New York Mellon`, sector: `Financials`, checkedAt: monday },
{ symbol: `BAX`, company: `Baxter International Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `BDX`, company: `Becton Dickinson`, sector: `Health Care`, checkedAt: monday },
{ symbol: `BRK.B`, company: `Berkshire Hathaway`, sector: `Financials`, checkedAt: monday },
{ symbol: `BBY`, company: `Best Buy Co. Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `BIO`, company: `Bio-Rad Laboratories`, sector: `Health Care`, checkedAt: monday },
{ symbol: `BIIB`, company: `Biogen Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `BLK`, company: `BlackRock`, sector: `Financials`, checkedAt: monday },
{ symbol: `BA`, company: `Boeing Company`, sector: `Industrials`, checkedAt: monday },
{ symbol: `BKNG`, company: `Booking Holdings Inc`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `BWA`, company: `BorgWarner`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `BXP`, company: `Boston Properties`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `BSX`, company: `Boston Scientific`, sector: `Health Care`, checkedAt: monday },
{ symbol: `BMY`, company: `Bristol-Myers Squibb`, sector: `Health Care`, checkedAt: monday },
{ symbol: `AVGO`, company: `Broadcom Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `BR`, company: `Broadridge Financial Solutions`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `BF.B`, company: `Brown-Forman Corp.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `CHRW`, company: `C. H. Robinson Worldwide`, sector: `Industrials`, checkedAt: monday },
{ symbol: `COG`, company: `Cabot Oil & Gas`, sector: `Energy`, checkedAt: monday },
{ symbol: `CDNS`, company: `Cadence Design Systems`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `CPB`, company: `Campbell Soup`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `COF`, company: `Capital One Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `CAH`, company: `Cardinal Health Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `KMX`, company: `Carmax Inc`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `CCL`, company: `Carnival Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `CARR`, company: `Carrier Global`, sector: `Industrials`, checkedAt: monday },
{ symbol: `CTLT`, company: `Catalent`, sector: `Health Care`, checkedAt: monday },
{ symbol: `CAT`, company: `Caterpillar Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `CBOE`, company: `Cboe Global Markets`, sector: `Financials`, checkedAt: monday },
{ symbol: `CBRE`, company: `CBRE Group`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `CDW`, company: `CDW`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `CE`, company: `Celanese`, sector: `Materials`, checkedAt: monday },
{ symbol: `CNC`, company: `Centene Corporation`, sector: `Health Care`, checkedAt: monday },
{ symbol: `CNP`, company: `CenterPoint Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `CERN`, company: `Cerner`, sector: `Health Care`, checkedAt: monday },
{ symbol: `CF`, company: `CF Industries Holdings Inc`, sector: `Materials`, checkedAt: monday },
{ symbol: `SCHW`, company: `Charles Schwab Corporation`, sector: `Financials`, checkedAt: monday },
{ symbol: `CHTR`, company: `Charter Communications`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `CVX`, company: `Chevron Corp.`, sector: `Energy`, checkedAt: monday },
{ symbol: `CMG`, company: `Chipotle Mexican Grill`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `CB`, company: `Chubb Limited`, sector: `Financials`, checkedAt: monday },
{ symbol: `CHD`, company: `Church & Dwight`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `CI`, company: `Cigna`, sector: `Health Care`, checkedAt: monday },
{ symbol: `CINF`, company: `Cincinnati Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `CTAS`, company: `Cintas Corporation`, sector: `Industrials`, checkedAt: monday },
{ symbol: `CSCO`, company: `Cisco Systems`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `C`, company: `Citigroup Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `CFG`, company: `Citizens Financial Group`, sector: `Financials`, checkedAt: monday },
{ symbol: `CTXS`, company: `Citrix Systems`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `CLX`, company: `The Clorox Company`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `CME`, company: `CME Group Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `CMS`, company: `CMS Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `KO`, company: `Coca-Cola Company`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `CTSH`, company: `Cognizant Technology Solutions`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `CL`, company: `Colgate-Palmolive`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `CMCSA`, company: `Comcast Corp.`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `CMA`, company: `Comerica Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `CAG`, company: `Conagra Brands`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `COP`, company: `ConocoPhillips`, sector: `Energy`, checkedAt: monday },
{ symbol: `ED`, company: `Consolidated Edison`, sector: `Utilities`, checkedAt: monday },
{ symbol: `STZ`, company: `Constellation Brands`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `COO`, company: `The Cooper Companies`, sector: `Health Care`, checkedAt: monday },
{ symbol: `CPRT`, company: `Copart Inc`, sector: `Industrials`, checkedAt: monday },
{ symbol: `GLW`, company: `Corning Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `CTVA`, company: `Corteva`, sector: `Materials`, checkedAt: monday },
{ symbol: `COST`, company: `Costco Wholesale Corp.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `CCI`, company: `Crown Castle`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `CSX`, company: `CSX Corp.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `CMI`, company: `Cummins Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `CVS`, company: `CVS Health`, sector: `Health Care`, checkedAt: monday },
{ symbol: `DHI`, company: `D. R. Horton`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `DHR`, company: `Danaher Corp.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `DRI`, company: `Darden Restaurants`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `DVA`, company: `DaVita Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `DE`, company: `Deere & Co.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `DAL`, company: `Delta Air Lines Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `XRAY`, company: `Dentsply Sirona`, sector: `Health Care`, checkedAt: monday },
{ symbol: `DVN`, company: `Devon Energy`, sector: `Energy`, checkedAt: monday },
{ symbol: `DXCM`, company: `DexCom`, sector: `Health Care`, checkedAt: monday },
{ symbol: `FANG`, company: `Diamondback Energy`, sector: `Energy`, checkedAt: monday },
{ symbol: `DLR`, company: `Digital Realty Trust Inc`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `DFS`, company: `Discover Financial Services`, sector: `Financials`, checkedAt: monday },
{ symbol: `DISCA`, company: `Discovery, Inc. (Series A)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `DISCK`, company: `Discovery, Inc. (Series C)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `DISH`, company: `Dish Network`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `DG`, company: `Dollar General`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `DLTR`, company: `Dollar Tree`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `D`, company: `Dominion Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `DPZ`, company: `Domino's Pizza`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `DOV`, company: `Dover Corporation`, sector: `Industrials`, checkedAt: monday },
{ symbol: `DOW`, company: `Dow Inc.`, sector: `Materials`, checkedAt: monday },
{ symbol: `DTE`, company: `DTE Energy Co.`, sector: `Utilities`, checkedAt: monday },
{ symbol: `DUK`, company: `Duke Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `DRE`, company: `Duke Realty Corp`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `DD`, company: `DuPont de Nemours Inc`, sector: `Materials`, checkedAt: monday },
{ symbol: `DXC`, company: `DXC Technology`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `EMN`, company: `Eastman Chemical`, sector: `Materials`, checkedAt: monday },
{ symbol: `ETN`, company: `Eaton Corporation`, sector: `Industrials`, checkedAt: monday },
{ symbol: `EBAY`, company: `eBay Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `ECL`, company: `Ecolab Inc.`, sector: `Materials`, checkedAt: monday },
{ symbol: `EIX`, company: `Edison Int'l`, sector: `Utilities`, checkedAt: monday },
{ symbol: `EW`, company: `Edwards Lifesciences`, sector: `Health Care`, checkedAt: monday },
{ symbol: `EA`, company: `Electronic Arts`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `EMR`, company: `Emerson Electric Company`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ENPH`, company: `Enphase Energy`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ETR`, company: `Entergy Corp.`, sector: `Utilities`, checkedAt: monday },
{ symbol: `EOG`, company: `EOG Resources`, sector: `Energy`, checkedAt: monday },
{ symbol: `EFX`, company: `Equifax Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `EQIX`, company: `Equinix`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `EQR`, company: `Equity Residential`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `ESS`, company: `Essex Property Trust, Inc.`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `EL`, company: `Estée Lauder Companies`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `ETSY`, company: `Etsy`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `EVRG`, company: `Evergy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `ES`, company: `Eversource Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `RE`, company: `Everest Re Group Ltd.`, sector: `Financials`, checkedAt: monday },
{ symbol: `EXC`, company: `Exelon Corp.`, sector: `Utilities`, checkedAt: monday },
{ symbol: `EXPE`, company: `Expedia Group`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `EXPD`, company: `Expeditors`, sector: `Industrials`, checkedAt: monday },
{ symbol: `EXR`, company: `Extra Space Storage`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `XOM`, company: `Exxon Mobil Corp.`, sector: `Energy`, checkedAt: monday },
{ symbol: `FFIV`, company: `F5 Networks`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FB`, company: `Facebook, Inc.`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `FAST`, company: `Fastenal Co`, sector: `Industrials`, checkedAt: monday },
{ symbol: `FRT`, company: `Federal Realty Investment Trust`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `FDX`, company: `FedEx Corporation`, sector: `Industrials`, checkedAt: monday },
{ symbol: `FIS`, company: `Fidelity National Information Services`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FITB`, company: `Fifth Third Bancorp`, sector: `Financials`, checkedAt: monday },
{ symbol: `FE`, company: `FirstEnergy Corp`, sector: `Utilities`, checkedAt: monday },
{ symbol: `FRC`, company: `First Republic Bank`, sector: `Financials`, checkedAt: monday },
{ symbol: `FISV`, company: `Fiserv Inc`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FLT`, company: `FleetCor Technologies Inc`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FLIR`, company: `FLIR Systems`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FLS`, company: `Flowserve Corporation`, sector: `Industrials`, checkedAt: monday },
{ symbol: `FMC`, company: `FMC Corporation`, sector: `Materials`, checkedAt: monday },
{ symbol: `F`, company: `Ford Motor Company`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `FTNT`, company: `Fortinet`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FTV`, company: `Fortive Corp`, sector: `Industrials`, checkedAt: monday },
{ symbol: `FBHS`, company: `Fortune Brands Home & Security`, sector: `Industrials`, checkedAt: monday },
{ symbol: `FOXA`, company: `Fox Corporation (Class A)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `FOX`, company: `Fox Corporation (Class B)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `BEN`, company: `Franklin Resources`, sector: `Financials`, checkedAt: monday },
{ symbol: `FCX`, company: `Freeport-McMoRan Inc.`, sector: `Materials`, checkedAt: monday },
{ symbol: `GPS`, company: `Gap Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `GRMN`, company: `Garmin Ltd.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `IT`, company: `Gartner Inc`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `GD`, company: `General Dynamics`, sector: `Industrials`, checkedAt: monday },
{ symbol: `GE`, company: `General Electric`, sector: `Industrials`, checkedAt: monday },
{ symbol: `GIS`, company: `General Mills`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `GM`, company: `General Motors`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `GPC`, company: `Genuine Parts`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `GILD`, company: `Gilead Sciences`, sector: `Health Care`, checkedAt: monday },
{ symbol: `GL`, company: `Globe Life Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `GPN`, company: `Global Payments Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `GS`, company: `Goldman Sachs Group`, sector: `Financials`, checkedAt: monday },
{ symbol: `GWW`, company: `Grainger (W.W.) Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `HAL`, company: `Halliburton Co.`, sector: `Energy`, checkedAt: monday },
{ symbol: `HBI`, company: `Hanesbrands Inc`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `HIG`, company: `Hartford Financial Svc.Gp.`, sector: `Financials`, checkedAt: monday },
{ symbol: `HAS`, company: `Hasbro Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `HCA`, company: `HCA Healthcare`, sector: `Health Care`, checkedAt: monday },
{ symbol: `PEAK`, company: `Healthpeak Properties`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `HSIC`, company: `Henry Schein`, sector: `Health Care`, checkedAt: monday },
{ symbol: `HSY`, company: `The Hershey Company`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `HES`, company: `Hess Corporation`, sector: `Energy`, checkedAt: monday },
{ symbol: `HPE`, company: `Hewlett Packard Enterprise`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `HLT`, company: `Hilton Worldwide Holdings Inc`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `HFC`, company: `HollyFrontier Corp`, sector: `Energy`, checkedAt: monday },
{ symbol: `HOLX`, company: `Hologic`, sector: `Health Care`, checkedAt: monday },
{ symbol: `HD`, company: `Home Depot`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `HON`, company: `Honeywell Int'l Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `HRL`, company: `Hormel Foods Corp.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `HST`, company: `Host Hotels & Resorts`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `HWM`, company: `Howmet Aerospace`, sector: `Industrials`, checkedAt: monday },
{ symbol: `HPQ`, company: `HP Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `HUM`, company: `Humana Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `HBAN`, company: `Huntington Bancshares`, sector: `Financials`, checkedAt: monday },
{ symbol: `HII`, company: `Huntington Ingalls Industries`, sector: `Industrials`, checkedAt: monday },
{ symbol: `IEX`, company: `IDEX Corporation`, sector: `Industrials`, checkedAt: monday },
{ symbol: `IDXX`, company: `Idexx Laboratories`, sector: `Health Care`, checkedAt: monday },
{ symbol: `INFO`, company: `IHS Markit`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ITW`, company: `Illinois Tool Works`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ILMN`, company: `Illumina Inc`, sector: `Health Care`, checkedAt: monday },
{ symbol: `INCY`, company: `Incyte`, sector: `Health Care`, checkedAt: monday },
{ symbol: `IR`, company: `Ingersoll Rand`, sector: `Industrials`, checkedAt: monday },
{ symbol: `INTC`, company: `Intel Corp.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ICE`, company: `Intercontinental Exchange`, sector: `Financials`, checkedAt: monday },
{ symbol: `IBM`, company: `International Business Machines`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `IP`, company: `International Paper`, sector: `Materials`, checkedAt: monday },
{ symbol: `IPG`, company: `Interpublic Group`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `IFF`, company: `International Flavors & Fragrances`, sector: `Materials`, checkedAt: monday },
{ symbol: `INTU`, company: `Intuit Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ISRG`, company: `Intuitive Surgical Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `IVZ`, company: `Invesco Ltd.`, sector: `Financials`, checkedAt: monday },
{ symbol: `IPGP`, company: `IPG Photonics Corp.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `IQV`, company: `IQVIA Holdings Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `IRM`, company: `Iron Mountain Incorporated`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `JKHY`, company: `Jack Henry & Associates`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `J`, company: `Jacobs Engineering Group`, sector: `Industrials`, checkedAt: monday },
{ symbol: `JBHT`, company: `J. B. Hunt Transport Services`, sector: `Industrials`, checkedAt: monday },
{ symbol: `SJM`, company: `JM Smucker`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `JNJ`, company: `Johnson & Johnson`, sector: `Health Care`, checkedAt: monday },
{ symbol: `JCI`, company: `Johnson Controls International`, sector: `Industrials`, checkedAt: monday },
{ symbol: `JPM`, company: `JPMorgan Chase & Co.`, sector: `Financials`, checkedAt: monday },
{ symbol: `JNPR`, company: `Juniper Networks`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `KSU`, company: `Kansas City Southern`, sector: `Industrials`, checkedAt: monday },
{ symbol: `K`, company: `Kellogg Co.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `KEY`, company: `KeyCorp`, sector: `Financials`, checkedAt: monday },
{ symbol: `KEYS`, company: `Keysight Technologies`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `KMB`, company: `Kimberly-Clark`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `KIM`, company: `Kimco Realty`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `KMI`, company: `Kinder Morgan`, sector: `Energy`, checkedAt: monday },
{ symbol: `KLAC`, company: `KLA Corporation`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `KHC`, company: `Kraft Heinz Co`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `KR`, company: `Kroger Co.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `LB`, company: `L Brands Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `LHX`, company: `L3Harris Technologies`, sector: `Industrials`, checkedAt: monday },
{ symbol: `LH`, company: `Laboratory Corp. of America Holding`, sector: `Health Care`, checkedAt: monday },
{ symbol: `LRCX`, company: `Lam Research`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `LW`, company: `Lamb Weston Holdings Inc`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `LVS`, company: `Las Vegas Sands`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `LEG`, company: `Leggett & Platt`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `LDOS`, company: `Leidos Holdings`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `LEN`, company: `Lennar Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `LLY`, company: `Lilly (Eli) & Co.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `LNC`, company: `Lincoln National`, sector: `Financials`, checkedAt: monday },
{ symbol: `LIN`, company: `Linde plc`, sector: `Materials`, checkedAt: monday },
{ symbol: `LYV`, company: `Live Nation Entertainment`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `LKQ`, company: `LKQ Corporation`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `LMT`, company: `Lockheed Martin Corp.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `L`, company: `Loews Corp.`, sector: `Financials`, checkedAt: monday },
{ symbol: `LOW`, company: `Lowe's Cos.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `LUMN`, company: `Lumen Technologies`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `LYB`, company: `LyondellBasell`, sector: `Materials`, checkedAt: monday },
{ symbol: `MTB`, company: `M&T Bank`, sector: `Financials`, checkedAt: monday },
{ symbol: `MRO`, company: `Marathon Oil Corp.`, sector: `Energy`, checkedAt: monday },
{ symbol: `MPC`, company: `Marathon Petroleum`, sector: `Energy`, checkedAt: monday },
{ symbol: `MKTX`, company: `MarketAxess`, sector: `Financials`, checkedAt: monday },
{ symbol: `MAR`, company: `Marriott International`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `MMC`, company: `Marsh & McLennan`, sector: `Financials`, checkedAt: monday },
{ symbol: `MLM`, company: `Martin Marietta Materials`, sector: `Materials`, checkedAt: monday },
{ symbol: `MAS`, company: `Masco Corp.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `MA`, company: `Mastercard Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `MKC`, company: `McCormick & Co.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `MXIM`, company: `Maxim Integrated Products`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `MCD`, company: `McDonald's Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `MCK`, company: `McKesson Corp.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `MDT`, company: `Medtronic plc`, sector: `Health Care`, checkedAt: monday },
{ symbol: `MRK`, company: `Merck & Co.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `MET`, company: `MetLife Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `MTD`, company: `Mettler Toledo`, sector: `Health Care`, checkedAt: monday },
{ symbol: `MGM`, company: `MGM Resorts International`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `MCHP`, company: `Microchip Technology`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `MU`, company: `Micron Technology`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `MSFT`, company: `Microsoft Corp.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `MAA`, company: `Mid-America Apartments`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `MHK`, company: `Mohawk Industries`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `TAP`, company: `Molson Coors Beverage Company`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `MDLZ`, company: `Mondelez International`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `MNST`, company: `Monster Beverage`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `MCO`, company: `Moody's Corp`, sector: `Financials`, checkedAt: monday },
{ symbol: `MS`, company: `Morgan Stanley`, sector: `Financials`, checkedAt: monday },
{ symbol: `MOS`, company: `The Mosaic Company`, sector: `Materials`, checkedAt: monday },
{ symbol: `MSI`, company: `Motorola Solutions Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `MSCI`, company: `MSCI Inc`, sector: `Financials`, checkedAt: monday },
{ symbol: `NDAQ`, company: `Nasdaq, Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `NTAP`, company: `NetApp`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `NFLX`, company: `Netflix Inc.`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `NWL`, company: `Newell Brands`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `NEM`, company: `Newmont Corporation`, sector: `Materials`, checkedAt: monday },
{ symbol: `NWSA`, company: `News Corp (Class A)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `NWS`, company: `News Corp (Class B)`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `NEE`, company: `NextEra Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `NLSN`, company: `Nielsen Holdings`, sector: `Industrials`, checkedAt: monday },
{ symbol: `NKE`, company: `Nike, Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `NI`, company: `NiSource Inc.`, sector: `Utilities`, checkedAt: monday },
{ symbol: `NSC`, company: `Norfolk Southern Corp.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `NTRS`, company: `Northern Trust Corp.`, sector: `Financials`, checkedAt: monday },
{ symbol: `NOC`, company: `Northrop Grumman`, sector: `Industrials`, checkedAt: monday },
{ symbol: `NLOK`, company: `NortonLifeLock`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `NCLH`, company: `Norwegian Cruise Line Holdings`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `NOV`, company: `NOV Inc.`, sector: `Energy`, checkedAt: monday },
{ symbol: `NRG`, company: `NRG Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `NUE`, company: `Nucor Corp.`, sector: `Materials`, checkedAt: monday },
{ symbol: `NVDA`, company: `Nvidia Corporation`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `NVR`, company: `NVR, Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `ORLY`, company: `O'Reilly Automotive`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `OXY`, company: `Occidental Petroleum`, sector: `Energy`, checkedAt: monday },
{ symbol: `ODFL`, company: `Old Dominion Freight Line`, sector: `Industrials`, checkedAt: monday },
{ symbol: `OMC`, company: `Omnicom Group`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `OKE`, company: `Oneok`, sector: `Energy`, checkedAt: monday },
{ symbol: `ORCL`, company: `Oracle Corp.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `OTIS`, company: `Otis Worldwide`, sector: `Industrials`, checkedAt: monday },
{ symbol: `PCAR`, company: `Paccar`, sector: `Industrials`, checkedAt: monday },
{ symbol: `PKG`, company: `Packaging Corporation of America`, sector: `Materials`, checkedAt: monday },
{ symbol: `PH`, company: `Parker-Hannifin`, sector: `Industrials`, checkedAt: monday },
{ symbol: `PAYX`, company: `Paychex Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `PAYC`, company: `Paycom`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `PYPL`, company: `PayPal`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `PNR`, company: `Pentair plc`, sector: `Industrials`, checkedAt: monday },
{ symbol: `PBCT`, company: `People's United Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `PEP`, company: `PepsiCo Inc.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `PKI`, company: `PerkinElmer`, sector: `Health Care`, checkedAt: monday },
{ symbol: `PRGO`, company: `Perrigo`, sector: `Health Care`, checkedAt: monday },
{ symbol: `PFE`, company: `Pfizer Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `PM`, company: `Philip Morris International`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `PSX`, company: `Phillips 66`, sector: `Energy`, checkedAt: monday },
{ symbol: `PNW`, company: `Pinnacle West Capital`, sector: `Utilities`, checkedAt: monday },
{ symbol: `PXD`, company: `Pioneer Natural Resources`, sector: `Energy`, checkedAt: monday },
{ symbol: `PNC`, company: `PNC Financial Services`, sector: `Financials`, checkedAt: monday },
{ symbol: `POOL`, company: `Pool Corporation`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `PPG`, company: `PPG Industries`, sector: `Materials`, checkedAt: monday },
{ symbol: `PPL`, company: `PPL Corp.`, sector: `Utilities`, checkedAt: monday },
{ symbol: `PFG`, company: `Principal Financial Group`, sector: `Financials`, checkedAt: monday },
{ symbol: `PG`, company: `Procter & Gamble`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `PGR`, company: `Progressive Corp.`, sector: `Financials`, checkedAt: monday },
{ symbol: `PLD`, company: `Prologis`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `PRU`, company: `Prudential Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `PEG`, company: `Public Service Enterprise Group (PSEG)`, sector: `Utilities`, checkedAt: monday },
{ symbol: `PSA`, company: `Public Storage`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `PHM`, company: `PulteGroup`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `PVH`, company: `PVH Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `QRVO`, company: `Qorvo`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `PWR`, company: `Quanta Services Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `QCOM`, company: `Qualcomm`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `DGX`, company: `Quest Diagnostics`, sector: `Health Care`, checkedAt: monday },
{ symbol: `RL`, company: `Ralph Lauren Corporation`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `RJF`, company: `Raymond James Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `RTX`, company: `Raytheon Technologies`, sector: `Industrials`, checkedAt: monday },
{ symbol: `O`, company: `Realty Income Corporation`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `REG`, company: `Regency Centers Corporation`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `REGN`, company: `Regeneron Pharmaceuticals`, sector: `Health Care`, checkedAt: monday },
{ symbol: `RF`, company: `Regions Financial Corp.`, sector: `Financials`, checkedAt: monday },
{ symbol: `RSG`, company: `Republic Services Inc`, sector: `Industrials`, checkedAt: monday },
{ symbol: `RMD`, company: `ResMed`, sector: `Health Care`, checkedAt: monday },
{ symbol: `RHI`, company: `Robert Half International`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ROK`, company: `Rockwell Automation Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ROL`, company: `Rollins, Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ROP`, company: `Roper Technologies`, sector: `Industrials`, checkedAt: monday },
{ symbol: `ROST`, company: `Ross Stores`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `RCL`, company: `Royal Caribbean Group`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `SPGI`, company: `S&P Global Inc.`, sector: `Financials`, checkedAt: monday },
{ symbol: `CRM`, company: `Salesforce.com`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `SBAC`, company: `SBA Communications`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `SLB`, company: `Schlumberger Ltd.`, sector: `Energy`, checkedAt: monday },
{ symbol: `STX`, company: `Seagate Technology`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `SEE`, company: `Sealed Air`, sector: `Materials`, checkedAt: monday },
{ symbol: `SRE`, company: `Sempra Energy`, sector: `Utilities`, checkedAt: monday },
{ symbol: `NOW`, company: `ServiceNow`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `SHW`, company: `Sherwin-Williams`, sector: `Materials`, checkedAt: monday },
{ symbol: `SPG`, company: `Simon Property Group Inc`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `SWKS`, company: `Skyworks Solutions`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `SLG`, company: `SL Green Realty`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `SNA`, company: `Snap-on`, sector: `Industrials`, checkedAt: monday },
{ symbol: `SO`, company: `Southern Company`, sector: `Utilities`, checkedAt: monday },
{ symbol: `LUV`, company: `Southwest Airlines`, sector: `Industrials`, checkedAt: monday },
{ symbol: `SWK`, company: `Stanley Black & Decker`, sector: `Industrials`, checkedAt: monday },
{ symbol: `SBUX`, company: `Starbucks Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `STT`, company: `State Street Corp.`, sector: `Financials`, checkedAt: monday },
{ symbol: `STE`, company: `Steris`, sector: `Health Care`, checkedAt: monday },
{ symbol: `SYK`, company: `Stryker Corp.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `SIVB`, company: `SVB Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `SYF`, company: `Synchrony Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `SNPS`, company: `Synopsys Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `SYY`, company: `Sysco Corp.`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `TMUS`, company: `T-Mobile US`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `TROW`, company: `T. Rowe Price Group`, sector: `Financials`, checkedAt: monday },
{ symbol: `TTWO`, company: `Take-Two Interactive`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `TPR`, company: `Tapestry, Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `TGT`, company: `Target Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `TEL`, company: `TE Connectivity Ltd.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `FTI`, company: `TechnipFMC`, sector: `Energy`, checkedAt: monday },
{ symbol: `TDY`, company: `Teledyne Technologies`, sector: `Industrials`, checkedAt: monday },
{ symbol: `TFX`, company: `Teleflex`, sector: `Health Care`, checkedAt: monday },
{ symbol: `TER`, company: `Teradyne`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `TSLA`, company: `Tesla, Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `TXN`, company: `Texas Instruments`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `TXT`, company: `Textron Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `TMO`, company: `Thermo Fisher Scientific`, sector: `Health Care`, checkedAt: monday },
{ symbol: `TJX`, company: `TJX Companies Inc.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `TSCO`, company: `Tractor Supply Company`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `TT`, company: `Trane Technologies plc`, sector: `Industrials`, checkedAt: monday },
{ symbol: `TDG`, company: `TransDigm Group`, sector: `Industrials`, checkedAt: monday },
{ symbol: `TRV`, company: `The Travelers Companies`, sector: `Financials`, checkedAt: monday },
{ symbol: `TRMB`, company: `Trimble Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `TFC`, company: `Truist Financial`, sector: `Financials`, checkedAt: monday },
{ symbol: `TWTR`, company: `Twitter, Inc.`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `TYL`, company: `Tyler Technologies`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `TSN`, company: `Tyson Foods`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `UDR`, company: `UDR, Inc.`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `ULTA`, company: `Ulta Beauty`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `USB`, company: `U.S. Bancorp`, sector: `Financials`, checkedAt: monday },
{ symbol: `UAA`, company: `Under Armour (Class A)`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `UA`, company: `Under Armour (Class C)`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `UNP`, company: `Union Pacific Corp`, sector: `Industrials`, checkedAt: monday },
{ symbol: `UAL`, company: `United Airlines Holdings`, sector: `Industrials`, checkedAt: monday },
{ symbol: `UNH`, company: `UnitedHealth Group Inc.`, sector: `Health Care`, checkedAt: monday },
{ symbol: `UPS`, company: `United Parcel Service`, sector: `Industrials`, checkedAt: monday },
{ symbol: `URI`, company: `United Rentals, Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `UHS`, company: `Universal Health Services`, sector: `Health Care`, checkedAt: monday },
{ symbol: `UNM`, company: `Unum Group`, sector: `Financials`, checkedAt: monday },
{ symbol: `VLO`, company: `Valero Energy`, sector: `Energy`, checkedAt: monday },
{ symbol: `VAR`, company: `Varian Medical Systems`, sector: `Health Care`, checkedAt: monday },
{ symbol: `VTR`, company: `Ventas Inc`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `VRSN`, company: `Verisign Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `VRSK`, company: `Verisk Analytics`, sector: `Industrials`, checkedAt: monday },
{ symbol: `VZ`, company: `Verizon Communications`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `VRTX`, company: `Vertex Pharmaceuticals Inc`, sector: `Health Care`, checkedAt: monday },
{ symbol: `VFC`, company: `VF Corporation`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `VIAC`, company: `ViacomCBS`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `VTRS`, company: `Viatris`, sector: `Health Care`, checkedAt: monday },
{ symbol: `V`, company: `Visa Inc.`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `VNT`, company: `Vontier`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `VNO`, company: `Vornado Realty Trust`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `VMC`, company: `Vulcan Materials`, sector: `Materials`, checkedAt: monday },
{ symbol: `WRB`, company: `W. R. Berkley Corporation`, sector: `Financials`, checkedAt: monday },
{ symbol: `WAB`, company: `Westinghouse Air Brake Technologies Corp`, sector: `Industrials`, checkedAt: monday },
{ symbol: `WMT`, company: `Walmart`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `WBA`, company: `Walgreens Boots Alliance`, sector: `Consumer Staples`, checkedAt: monday },
{ symbol: `DIS`, company: `The Walt Disney Company`, sector: `Communication Services`, checkedAt: monday },
{ symbol: `WM`, company: `Waste Management Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `WAT`, company: `Waters Corporation`, sector: `Health Care`, checkedAt: monday },
{ symbol: `WEC`, company: `WEC Energy Group`, sector: `Utilities`, checkedAt: monday },
{ symbol: `WFC`, company: `Wells Fargo`, sector: `Financials`, checkedAt: monday },
{ symbol: `WELL`, company: `Welltower Inc.`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `WST`, company: `West Pharmaceutical Services`, sector: `Health Care`, checkedAt: monday },
{ symbol: `WDC`, company: `Western Digital`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `WU`, company: `Western Union Co`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `WRK`, company: `WestRock`, sector: `Materials`, checkedAt: monday },
{ symbol: `WY`, company: `Weyerhaeuser`, sector: `Real Estate`, checkedAt: monday },
{ symbol: `WHR`, company: `Whirlpool Corp.`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `WMB`, company: `Williams Companies`, sector: `Energy`, checkedAt: monday },
{ symbol: `WLTW`, company: `Willis Towers Watson`, sector: `Financials`, checkedAt: monday },
{ symbol: `WYNN`, company: `Wynn Resorts Ltd`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `XEL`, company: `Xcel Energy Inc`, sector: `Utilities`, checkedAt: monday },
{ symbol: `XRX`, company: `Xerox`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `XLNX`, company: `Xilinx`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `XYL`, company: `Xylem Inc.`, sector: `Industrials`, checkedAt: monday },
{ symbol: `YUM`, company: `Yum! Brands Inc`, sector: `Consumer Discretionary`, checkedAt: monday },
{ symbol: `ZBRA`, company: `Zebra Technologies`, sector: `Information Technology`, checkedAt: monday },
{ symbol: `ZBH`, company: `Zimmer Biomet`, sector: `Health Care`, checkedAt: monday },
{ symbol: `ZION`, company: `Zions Bancorp`, sector: `Financials`, checkedAt: monday },
{ symbol: `ZTS`, company: `Zoetis`, sector: `Health Care`, checkedAt: monday },
])